package com.tutorac.oop.abstraction;

public class Assignment8 {
    // PARTIAL ABSTRACTION
    // CREATE A CLASS CALLED AS RADIO
    // DECLARE PROPERTIES OF RADIO
    // DECLARE METHODS TO TURN ON, TURN OFF AND TUNE INTO A PARTICULAR FREQUENCY
    // DECLARE AN ABSTRACT CLASS CALLED AS RADIOTRANSMISSION
    // RADIO SHOULD EXTEND RADIOTRANSMISSION
    // DECLARE METHODS TO BROADCAST IN RADIOTRANSMISSION CLASS
    // CALL ABSTRACT CLASS METHODS IN RADIO CLASS

    // COMPLETE ABSTRACTION
    // CREATE AN INTERFACE CALLED Http
    // DECLARE METHOD DECLARATIONS LIKE 'GETDATA', 'POSTDATA', 'UPDATEDATA', 'DELETEDATA', 'SHOWMETADATA' etc
    // IN THE Http
    // CREATE A CLASS CALLED AS ChromeBrowser
    // ChromeBrowser SHOULD IMPLEMENT Http
    // OVERRIDE AND IMPLEMENT THE METHODS OF Http
    // CREATE ANOTHER CLASS CALLED AS EdgeBrowser
    // EdgeBrowser SHOULD IMPLEMENT Http
    // OVERRIDE AND IMPLEMENT THE METHODS OF Http
    // DECLARE A ChromeBrowser AND INVOKE METHODS ON IT
    // UPDATE THE ChromeBrowser TO EdgeBrowser AND CHECK CHANGES IN BEHAVIOR
}
