package com.tutorac.oop.core;

public class Assignment4 {
    // CREATE A BLUEPRINT OF A COMPUTER
    // ASSIGN PROPERTIES
    // CREATE DIFFERENT INSTANCES OF COMPUTER LIKE LENOVO, HP, APPLE MACBOOK
    // ASSIGN DIFFERENT VALUES TO EACH INSTANCE OR OBJECT
}
